let laughter=[
"    What do you call a broke actor? Johnny Debt.",
"What's better, Google or Yahoo? Let's Google it.",
"Which day do chickens hate the most? Friday.",
"You know about Pizza Hut? More like Pizza Butt.",
"What do you call a pile of cats? A Meowtain.",
"What washes up on small beaches? Microwaves.",
"What's the fastest way to lose a few pounds? Exit the European Union.",
"I wanna be rich enough to realize that I can't buy happiness.",
"How did Reese ate morning cereal? Witherspoon.",
"Where do police put their drinks? Copholders.",
"What happened to the octopus in the football game? He had tentackles.",
"How did the barber win the race? He knew a short cut.",
"Why are atheists so light? They have no mass.",
"Some say Tiger Woods is the greatest golfer of all time. I say he's sub-par at best.",
"A horse walks into a bar. The bartender says 'why the long face?",
"Best Funny Dad Jokes",

"Best Dad Joke Puns",
"What is a bear's favourite drink? Koka-Koala.",
"How does a blonde kill a worm? She burys it.",
"What is the most common blood type among pessimists? B Negative.",
"What kind of cat should you take into the desert ? A first aid kitty",
"I got gas today for $1.09! Too bad it was from Taco Bell.",
"What's the laziest piece of clothing? Underwear. It just sits on its butt all day.",
"I love my electric toothbrush, but sometimes I just have to break out the acoustic.",
"What did the number zero say to the number eight? Nice belt.",
"What is a chefs weapon of choice? A salt rifle.",
"Why are doctors always calm? They have a lot of patients.",
"Boss just announced he is leaving early. What a coincidence. So am I.",
"How much does a Hipster weigh? An Instagram.",
"What happens when an egg laughs? He cracks up",
"What kind of car does a rich shepherd drive? A Lamb-orghini!",
"Which one of the ten men won the pun contest? No pun in ten did.",
"Why are Saturday and Sunday so strong? Because the rest are weekdays.",
"Where does Santa stash his money? In a snowbank.",
"What is the dogs favourite city? New Yorkie.",
"What do sharks eat for lunch? Fish and ships.",
"How do trees get on the Internet? They log in.",
"No matter how much you push the envelope, it's still stationery.",
"Why wasn't the astronaut paying attention? Because he was spaced out.",
"Why do people procrastinate? I'll tell you later.",
"What did the grizzly bear study at college? He was an Ursa Major.",
"What's the worst cut of steak? Amazon Prime.",
"Where did the hipster drown? In the mainstream.",
"How do you advertise a motor home? A trailer.",
"What kind of shoes do therapists wear? Issues.",
"I went the other day to buy some camo pants, but could not find any.",
"Which is the cheapest bicycle you can buy? A penny-farthing.",
"What makes you sweat during the summer? A sweater.",
"Going commando is the closest I'll ever get to joining the army.",
"How does Moses prepare his coffee? Hebrews it.",
"I can't believe I got fired from the calendar factory. All I did was take a day off.",
"What can be served but not eaten? A tennis ball.",
"What stories are told by basketball players? Tall stories!",
"Today I gave my dead batteries away. Free of charge!",
"What kind of money does Mario use? 8-bitcoins.",
"Why is it more expensive to use air pumps nowadays? Inflation.",
"I stayed up all night wondering where the sun went. Then it dawned on me.",
"What sort of shoes do ninjas wear? Sneakers.",
"What is the Hulk's favorite fruit? Avocado.",
"Children are like farts. You can only tolerate your own.",
"Why is a river really rich? Its got two banks.",
"How many lawyers does it take to screw in a light bulb? None, lawyers only screw us.",
"What do you call a sunburnt santa? Crisp Cringle.",
"What's your dad getting for Christmas? Bald and fat.",
"What do you call a child afraid of Santa? Claustrophobic.",
"What's the most messed up trap for Santa? A Nicolas Cage.",
"Never lie! Said Mommy to little Timmy and handed him over to Santa.",
"What do you call a search engine that sings Christmas songs? Michael google.",
"What did Adam say to Eve on the day before Christmas? 'It's Christmas, Eve.'",
"You know youre getting old when Santa starts looking younger.",
"What does Santa and Hackers have in common? They both steal cookies.",
"What's the difference between Santa Claus and a bassist? Santa Claus has gifts.",
"What do Santa's little helpers learn in school? The Elfabet.",
"How did Darth Vader know what Luke got him for Christmas? He felt his presents.",
"How is Santa able to carry so many presents at once? Santa isn't real.",
"What did the horse say to Santa? Nothing, horses can not speak.",
"I got a sweater for Christmas. I really wanted a screamer or a moaner.",
"I like you. You remind me of when I was young and stupid.",
"I didn't know how badly we're losing the war on stupidity til I joined Facebook.",
"How can if you have a stupid dog ? It chases parked cars.",
"Sometimes the smartest thing you can do, is play stupid.",
"my New Years resolution is to stop making stupid New Years resolutions. I failed.",
"Worrying is so stupid. It's like carrying an umbrella waiting for it to rain.",
"What's the one thing a mechanic can't fix? Stupid.",
"I asked my mom something really stupid. I asked her to calm down.",
"Before Twitter, I used to be stupid in the privacy of my own mind.",
"What do you call a stupid fish? A dumb bass I'll sea myself trout.",
"Have you heard the joke they don't tell stupid people?",
"How do you choose a stupid policeman from a group of policemen? At random.",
"People don't realize how hard it is to write stupid things on a regular basis.",
"Want to know why fish tanks are stupid They don't even have a military.",
"A clever person solves a problem. A wise person avoids it. A stupid person makes it.",
"What animal is best at hitting a baseball? A bat.",
"What did Luke Skywalker get for his 16th birthday? A Toy-Yoda",
"What's the best thing about twenty nine year olds? There's 20 of them.",
"What do you call a gassy Scotsman? Bravefart.",
"What did the bicycle call its dad? Pop-cycle.",
"What do you call a pen without style? Stylus.",
"What is it called when two birds kiss? A Peck.",
"Why did the whale like the diver? Because he had flippers!",
"What do you call an empty harbour? An air-port",
"What do you call a boat with a hole? A sink.",
"What do you call a broken boomerang? A stick.",
"How did I get from Afghanistan to Iraq? Iran.",
"How does a restaurant make $1 million. You start with $2 million.",
"A clever person solves a problem. A wise person avoids it. A stupid person makes it.",
"What building has the most stories? A library.",
"How many push-ups can Chuck Norris do? All of them.",
"Time waits for no man. Unless that man is Chuck Norris.",
"Luke Skywalker uses the Force. The Force uses Chuck Norris.",
"If Chuck Norris is running late, time slows down. It knows better.",
"Chuck Norris can start a fire by rubbing two ice cubes together.",
"Chuck Norris is not Politically Correct. He is just Correct.",
"To be or not to be? That is the question. The answer? Chuck Norris.",
"Did you know that Chuck Norris was born in a log cabin? That he built.",
"Someone gave Chuck Norris the finger. He still has it.",
"Chuck Norris doesn't call the wrong number. You answer the wrong phone.",
"In a fight between Batman and Darth Vader, the winner would be Chuck Norris.",
"Chuck Norris does not get frostbite. Chuck Norris bites frost.",
"When Chuck Norris plays Monopoly, it affects the actual world economy.",
"When Chuck Norris goes swimming he doesn't get wet. The water gets Chuck Norris.",
"Who would rule in a dog world ? The pawlice.",
"I went to a bingo hall last night. It was good seeing some old faces.",
"How do you find Will Smith in a snow storm? You look for fresh prints.",
"What did Leonardo DiCaprio say when he planted a seed? Inception.",
"What do you call a cashew in space? An astronut.",
"I once farted in an elevator it was wrong on so many levels.",
"I've never been a great salesman. I'll tell you that for free",
"Who lost the presidential debate? We Americans.",
"What do you call a Slavic spouse? Czech-mate.",
"You know what the best thing is about being a narcissist? Me.",
"There are 3 kinds of people in the world those who can count and those who can't.",
"Why can't short people cook? Because the steaks are too high.",
"You know what I find odd? Every other number.",
"Why are automatic vehicles difficult to drive? Because they don't come with a manual.",
"What kind of clothes do lawyers wear? Lawsuits.",
"Best Hilarious Dad Jokes",
"What do you call it when water is poured over a clock? Time dilution.",
"Why did the walrus go to the tupperware factory? To get a tight seal.",
"What's the richest kind of air? A millionaire.",
"Did you know crocodiles can grow up to 15 feet? But most only have 4 .",
"So I decided to write a song about tortillas. Well, it's actually more of a wrap.",
"How does an elephant get down from a tree? He sits on a leaf and waits till autumn.",
"What does a nut say when it sneezes? Cashew.",
"Why did the accountant cross the road? Because that's what they did last year.",
"When I woke up today, I had no plans to be awesome, it just happened.",
"What do you call a fragile camera? A glass Canon.",
"I bought these pants 50% off. I guess they're shorts now.",
"Which dog is always without a tail? A hot dog.",
"Want to hear a construction joke? Sorry, still working on it.",
"What do you call a pig in a trailer? Pulled pork.",
"What is a knight's favourite fish? A swordfish.",

"What do you call an elf that sings? A wrapper.",
"Why did the Hipster burn his lip? He drank coffee before it was cool.",
"What do you call a young gold digger? A miner.",
"Why do we blink subconsciously? You aren't now.",
"Why was the cat afraid of the tree? Because of the tree bark.",
"Did you here about the two guys that stole a calendar? They each got six months.",
"Why couldn't you trust the king of the jungle? He was a lion.",
"What is green and has wheels? Grass, I lied about the wheels.",
"How do chickens get strong? They egg-cersize.",
"What do you call a funny psychic? A comedium.",
"What does former Vice President Gore play on the guitar? An algorithm.",
"Why should you never date a tennis player? Love means nothing to them.",
"I have great muscle memory I totally remember when I was in shape.",
"Internet explorer. The best browser for downloading a new browser.",
"How many men does it take to close the toilet seat? No one knows yet.",
"What is the longest rope in the world? Europe."
]


$(".btn").click((e)=>{
    e.preventDefault();
    let length = laughter.length;
    let random = Math.floor(Math.random() * length);
    let select_joke =  laughter[random];
    $(".joke").html(select_joke);
});

